/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/0001': RouteRecordInfo<'/posts/0001', '/posts/0001', Record<never, never>, Record<never, never>>,
    '/posts/0002': RouteRecordInfo<'/posts/0002', '/posts/0002', Record<never, never>, Record<never, never>>,
    '/posts/0003': RouteRecordInfo<'/posts/0003', '/posts/0003', Record<never, never>, Record<never, never>>,
    '/posts/0004': RouteRecordInfo<'/posts/0004', '/posts/0004', Record<never, never>, Record<never, never>>,
    '/posts/0005': RouteRecordInfo<'/posts/0005', '/posts/0005', Record<never, never>, Record<never, never>>,
    '/posts/0006': RouteRecordInfo<'/posts/0006', '/posts/0006', Record<never, never>, Record<never, never>>,
    '/posts/0007': RouteRecordInfo<'/posts/0007', '/posts/0007', Record<never, never>, Record<never, never>>,
    '/posts/0008': RouteRecordInfo<'/posts/0008', '/posts/0008', Record<never, never>, Record<never, never>>,
    '/posts/0009': RouteRecordInfo<'/posts/0009', '/posts/0009', Record<never, never>, Record<never, never>>,
    '/posts/0010': RouteRecordInfo<'/posts/0010', '/posts/0010', Record<never, never>, Record<never, never>>,
    '/posts/0011': RouteRecordInfo<'/posts/0011', '/posts/0011', Record<never, never>, Record<never, never>>,
    '/posts/0012': RouteRecordInfo<'/posts/0012', '/posts/0012', Record<never, never>, Record<never, never>>,
    '/posts/0013': RouteRecordInfo<'/posts/0013', '/posts/0013', Record<never, never>, Record<never, never>>,
    '/posts/0014': RouteRecordInfo<'/posts/0014', '/posts/0014', Record<never, never>, Record<never, never>>,
    '/posts/0015': RouteRecordInfo<'/posts/0015', '/posts/0015', Record<never, never>, Record<never, never>>,
    '/posts/0016': RouteRecordInfo<'/posts/0016', '/posts/0016', Record<never, never>, Record<never, never>>,
    '/posts/0017': RouteRecordInfo<'/posts/0017', '/posts/0017', Record<never, never>, Record<never, never>>,
    '/posts/0018': RouteRecordInfo<'/posts/0018', '/posts/0018', Record<never, never>, Record<never, never>>,
    '/posts/0019': RouteRecordInfo<'/posts/0019', '/posts/0019', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
